name: "Check license"

on:
  push:
    branches:
      - master

jobs:
  checkLicense:
    runs-on: ubuntu-latest
    steps:
      - run: cmp -s LICENSE.txt addons/godot-css-theme/LICENSE.txt && echo "Same" || exit 1