name: "Test"


on:
  workflow_dispatch: {}
# Disable for now, an import problem with godot?
#  push:
#    branches:
#      - master

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:4.1.2
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Unit Test
        run: sh scripts/test.sh
        timeout-minutes: 1
