name: "Check license"

on:
  push:
    branches:
      - master

jobs:
  checkLicense:
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:3.3.2
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Unit Test
        run: sh scripts/test.sh
        timeout-minutes: 5